num1 = int(input("Enter First Number: "))
num2 = int(input("Enter Second Number: "))
print("\nAddition = ", num1+num2)
print("Subtraction = ", num1-num2)
print("Multiplication = ", num1*num2)
print("Division = ", num1/num2)